### Week 5-2 NumPy Practice Problems

In [2]:
import numpy as np

### Warm up
NumPy creation and indexing.

In [3]:
# 1. Creates 3x3 array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# 2. Creates array [0, 2, 4, 6, 8]
np.array([2*i for i in range(5)])

array([0, 2, 4, 6, 8])

In [7]:
# 3. 5 evenly spaced numbers from 0 to 1
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [9]:
# Array indexing, Gets elements > 5
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

### Problem 1
Convert an array of Celsius measurements to Fahrenheit.
Note: `fahrenheit = (Celsius * 9/5) + 32`.

In [12]:
def convert_to_fahrenheit_list(temperatures):
    temperatures = np.array(temperatures)
    convert = lambda temps : temps * 9 / 5 + 32
    return convert(temperatures)

In [13]:
print("Testing with a regular list:")
temps_list = [0, 10, 20, 30]
print(convert_to_fahrenheit_list(temps_list))

Testing with a regular list:
[32. 50. 68. 86.]


In [ ]:
def convert_to_fahrenheit_numpy_array(temperatures):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
print("\nTesting with a NumPy array:")
temps_array = np.array([0, 10, 20, 30])
print(convert_to_fahrenheit_numpy_array(temps_array))

### Problem 2
Use numpy to create a function that adds a border filled with zeros around an existing array.

*Hint*: Use numpy's `pad` function. See https://numpy.org/doc/stable/reference/generated/numpy.pad.html

Note: we did not cover this function in class, see if you are comfortable of reading numpy documents and learn on your own!

In [16]:
import numpy as np
def add_border(x):
    ans = np.pad(x, ((1,1), (1,1)), 'constant', constant_values=0)
    return ans

In [17]:
x = np.ones((1, 1))
claimed = add_border(x)
correct = np.zeros((3, 3))
correct[1, 1] = 1.0
assert claimed.shape == correct.shape
assert np.all(np.abs(claimed - correct) < 1e-8)

### Problem 3
Create an $n \times n$ numpy array filled with a checkerboard pattern of zeros and ones. The first entry should be the integer `0`. Assume $n \ge 2$.

In [ ]:
def make_checkerboard(n):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
correct = \
    [[0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0]]
assert np.all(correct == make_checkerboard(8))

In [ ]:
import numpy as np
x = np.arange(10)